---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: false
  pep8:
    enabled: true
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
ratings:
  paths:
  - "**.py"
exclude_paths:
  - "venv/*"
  - "fabfile.py"