---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
      - fec5ad98acb50ddac629bb419c3721c1
    config:
      languages:
        - python
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
    - '**.py'
exclude_paths:
  - 'venv/*'
  - 'fabfile.py'
  - 'tests/*'
