---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - 7b22f1df906bbdcd93d035c81b674a3a
    config:
      languages:
      - python
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
  - "venv/*"
  - "fabfile.py"
  - "tests/*"
