language: python

python:
  - '2.7'

addons:
  apt:
    packages:
      - python-pip
      - python-virtualenv

install:
  - pip install -r requirements.lock

virtualenv:
    system_site_packages: true

env:
  PYTHONPATH=.:$PYTHONPATH
  FLASK_ENV=TEST

before_script:
  - cp config/config.yml.sample config/config.yml
  - alembic upgrade head

script:
  - fab polish:ci
  - codeclimate-test-reporter